### PR TITLE
Dnd character

### LINKED ISSUE #168: dnd-character stub is actually the example solution
@BNAndras

### PR DESCRIPTION
**Pull request by glennj**
Fixes #168

### CODE REVIEW

**Comment by BNAndras** [comment]
Test suite shouldn't show how to calculate hitpoints. That was a lack of my imagination at the time. Instead we should check if it falls in a range between 6 and 14.

**Comment by BNAndras** [comment]
Otherwise, it looks good to me.

**Comment by BNAndras** [comment]
Looking at this closer now that I'm off work, but I'd suggest adding a comment that indicates the `...` needs to be replaced to pass the tests. That's what I did with `clock`.

**Comment by BNAndras** [comment]
Comment looks good. I was unsure about the indentation since re-indenting with CPO resulted in this:

```
data Character:
  | blank-character()
    with:
    method randomize-stats(self) -> Character:
        ...
    end
```

However, it looks like it's indenting the method line relative to `| blank-character()` line, not the one immediately before it.

```
data Character:
  | blank-character()
		  with:
        method randomize-stats(self) -> Character:
          ...
        end
```

becomes

```
data Character:
  | blank-character()
		  with:
    method randomize-stats(self) -> Character:
          ...
        end
```

There's no difference in behavior when `with:` and `method` are aligned with one another or not. The Pyret style guide also doesn't address this. Personally, I'd prefer your indenting of the methods relative to the `with:` since it flows better. I think the additional clarity is worth the very minor discrepancy with CPO.

**Comment by glennj** [comment]
> Test suite shouldn't show how to calculate hitpoints. 

I think it's fine as-is: plenty of other tracks do exactly this.

> There's no difference in behavior when `with:` and `method` are aligned with one another or not. The Pyret style guide also doesn't address this. Personally, I'd prefer your indenting relative to the `with:` since it flows better. I think the additional clarity is worth the very minor discrepancy with CPO

I used similar indenting to `sharing:`, with the method indented one level, except the whole `with:`  block indented to be "under" the particular variant.

**Pull request merged**
