### PR TITLE
Initial implementation of the clock exercise

### PR DESCRIPTION
**Pull request by BNAndras**

### CODE REVIEW

**Comment by BNAndras** [comment]
@BethanyG, would you mind doing a quick gut check on if I over-complicated this exercise? Using a data declaration for Clock seems a good fit here, especially once we have a syllabus to properly introduce it At the moment, it feels a big step up from previous exercises I drafted.

**Comment by BethanyG** [comment]
Will add it to my list!  IIRC, we had a similar issue in Python, where `Clock` required a class with all sorts of methods - including a `__repr__` and a `__str__` (_with or without optional composition from `datetime`_).  We had to add an [instruction append](https://github.com/exercism/python/blob/main/exercises/practice/clock/.docs/instructions.append.md) by way of explanation. 

We could do that here, referencing docs or going into the related concepts --  but let me get a quiet moment to really look at it.  😄

**Comment by BNAndras** [comment]
Ooh, that's a great idea. An instruction append would go a long way with the D&D Character exercise I was asking about in Discord earlier.

**Comment by BNAndras** [comment]
Since we're at 20+ exercises for launch, this review can be low priority, @BethanyG. Thanks for your help so far with the track.

**Comment by BNAndras** [comment]
It seems I can define an _equals method (https://pyret.org/docs/latest/equality.html#%28part._equality__equals%29) that Pyret will use to check equality. That might be a better approach than then manual `values-equal` implementation so I'll play with this a little and see if it's more flexible. That'll likely require bumping up the exercise difficulty.

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
